# Generated by Django 2.2.1 on 2019-05-29 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='arrival_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 600), verbose_name='Arrival time'),
            preserve_default=False,
        ),
    ]
