# Generated by Django 2.2.1 on 2019-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='arriving_time',
            field=models.DurationField(default=10),
            preserve_default=False,
        ),
    ]
