# Generated by Django 2.2.1 on 2019-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_arriving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='arriving_time',
            field=models.IntegerField(),
        ),
    ]
