# Generated by Django 2.2.1 on 2019-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='arrival_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Arrival time'),
        ),
    ]
