# Generated by Django 2.2.1 on 2019-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190529_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='arriving_time',
            field=models.DurationField(verbose_name='arriving time'),
        ),
    ]
