# Generated by Django 2.2.1 on 2019-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190529_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='arriving_time',
        ),
    ]
