# Generated by Django 2.2.1 on 2019-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_arriving_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='arriving_time',
            field=models.DateTimeField(null=True, verbose_name='arriving time'),
        ),
    ]
