# Generated by Django 2.2.1 on 2019-05-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_arriving_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='arriving_time',
        ),
    ]
