# Generated by Django 2.2.1 on 2019-05-29 08:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='waiting_phonenumber',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coming_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_queue',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_time_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_total_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_skip_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_total_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
