# Generated by Django 2.2.1 on 2019-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20190529_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dining_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coming_time',
            field=models.TextField(default=''),
        ),
    ]
